version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

    open-pull-requests-limit: 5
