import { BACKEND_URL } from "../util/constants"
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

export const serviceApi = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: `${BACKEND_URL}`,
    credentials: "include",
  }),
  endpoints: (builder) => ({}),
  reducerPath: "serviceApi",
  refetchOnReconnect: true,
  // Enhanced caching configuration for better mobile performance
  keepUnusedDataFor: 300, // Keep unused data for 5 minutes (default is 60 seconds)
  // This reduces API requests by keeping data in cache longer
  // Users navigating back/forth won't trigger unnecessary refetches
  tagTypes: [
    "RecruitingPostComments",
    "RecruitingPosts",
    "RecruitingPost",
    "Comment",
    "Order",
    "Orders",
    "Profile",
    "MyProfile",
    "Listing",
    "Contractor",
    "MyShips",
    "Service",
    "OrderWebhook",
    "ContractorInvite",
    "AllListings",
    "ContractorListings",
    "Chat",
    "Notifications",
    "Aggregates",
    "Aggregate",
    "Offers",
    "Offer",
    "PublicContracts",
    "ModerationReports",
    "SellerAnalytics",
    "AdminAlerts",
    "Blocklist",
    "OrgBlocklist",
    "OrderSettings",
    "MarketStats",
    "MarketListings",
    "MarketBids",
    "UserListings",
    "MyListings",
    "MarketCategories",
    "MarketItems",
    "PublicListings",
    "BuyOrderListings",
    "MarketListingOrders",
    "AggregateChart",
    "AggregateHistory",
    "GameItem",
    "Multiple",
    "AdminAuditLogs",
    "ContractorAuditLogs",
    "AvailabilityRequirement",
    "OrderLimits",
    "ContractorLanguages",
    "UserLanguages",
  ],
})
