/**
 * Generated RTK Query API slices (split by domain).
 * Import this module for side effects so all endpoints are injected into generatedApi.
 * For domain-specific types/hooks, import from the individual slice files, e.g.:
 *   import { starmapApi, useGetStarmapRouteQuery } from "@/store/api/starmap"
 *   import { v2_marketApi, useGetListingsQuery } from "@/store/api/v2/market"
 */

import "./admin"
import "./chats"
import "./commodities"
import "./comments"
import "./contractors"
import "./contracts"
import "./core"
import "./deliveries"
import "./email"
import "./market"
import "./moderation"
import "./notifications"
import "./offers"
import "./orders"
import "./profile"
import "./push"
import "./recruiting"
import "./services"
import "./ships"
import "./starmap"
import "./tokens"
import "./transactions"
import "./wiki"

// v2 API slices (auto-generated from v2 OpenAPI spec)
import "./v2/admin"
import "./v2/chats"
import "./v2/comments"
import "./v2/commodities"
import "./v2/contractors"
import "./v2/contracts"
import "./v2/deliveries"
import "./v2/email"
import "./v2/market"
import "./v2/moderation"
import "./v2/notifications"
import "./v2/offers"
import "./v2/orders"
import "./v2/profile"
import "./v2/push"
import "./v2/recruiting"
import "./v2/services"
import "./v2/ships"
import "./v2/starmap"
import "./v2/tokens"
import "./v2/transactions"
import "./v2/wiki"
